### ISSUE TITLE
Training on multiple GPUs

### ISSUE THREAD

**Issue by AndreiBlindu** [FakeEnd/iDNA_ABF#2]
Hi, I'm training the model on a cluster with multiple nodes and 4 GPUs for each node. 
Up to now I've been able to use only one GPU, selecting it with the -device argument, but now I want to scale on more GPUs and eventually on more than one node.

I've tried to modify the train.py script in the following way in order to force the code to run on multiple devices:
`os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3"  #str(config.device)`
But it does not work since only the GPU 0 is used.

Can you please tell me if there is any way to make the training run on multiple GPUs?
Thanks

**Comment by FakeEnd** [comment]
I think you can use `nn.DataParallel` to put model on multiple GPUs. You can insert the code at here  https://github.com/FakeEnd/iDNA_ABF/blob/6feae58080cb8a675590a1fbf3a956baf25142f3/frame/ModelManager.py#L31
Here is the link: https://pytorch.org/docs/stable/generated/torch.nn.DataParallel.html
```
>>> net = torch.nn.DataParallel(model, device_ids=[0, 1, 2])
>>> output = net(input_var)  # input_var can be on any device, including CPU
```

**Comment by AndreiBlindu** [comment]
> I think you can use `nn.DataParallel` to put model on multiple GPUs. You can insert the code at here
> 
> https://github.com/FakeEnd/iDNA_ABF/blob/6feae58080cb8a675590a1fbf3a956baf25142f3/frame/ModelManager.py#L31
> 
> 
> Here is the link: https://pytorch.org/docs/stable/generated/torch.nn.DataParallel.html
> ```
> >>> net = torch.nn.DataParallel(model, device_ids=[0, 1, 2])
> >>> output = net(input_var)  # input_var can be on any device, including CPU
> ```

Thank you, now it seems that it is using 4 GPUs but I got the following error
`ValueError: Expected input batch_size (64) to match target batch_size (16).`
at `loss = self.loss_func(logits.view(-1, self.config.num_class), label.view(-1))`
because there is a mismatch between the logit shape and the label shape. It looks like the training samples are not scattered, but copied as the number of gpu.

I tried searching for solutions but nothing has worked yet.
For example here (https://discuss.pytorch.org/t/dataparallel-expected-input-batch-size-64-to-match-target-batch-size-32/20504/6) someone suggested to convert the input into tensor before calling model.forward
I tried that but I cannot perform the conversion from tuple to tensor since we are working on 'str' data.

Do you have any ideas on how to solve the issue?

**Comment by FakeEnd** [comment]
I change the code like this:
```
if self.config.model == 'FusionDNAbert':
                self.model = FusionDNAbert.FusionBERT(self.config)
                self.model = torch.nn.DataParallel(self.model)
```
and add a line in train.py
```
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3"
```
But I didn't meet the problem you say. Can you check it again?

**Comment by AndreiBlindu** [comment]
> I change the code like this:
> 
> ```
> if self.config.model == 'FusionDNAbert':
>                 self.model = FusionDNAbert.FusionBERT(self.config)
>                 self.model = torch.nn.DataParallel(self.model)
> ```
> 
> and add a line in train.py
> 
> ```
> os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3"
> ```
> 
> But I didn't meet the problem you say. Can you check it again?

In order to be sure, I tried to reclone the repository since I had made some other modifications to the code, then I changed the code exactly as you suggested above. But I still have the error as before, I report the log below:

```2024-05-05_02:49:57 INFO: Adjust Model Over.
2024-05-05_02:49:57 INFO: Init Optimizer Over.
2024-05-05_02:49:57 INFO: Define Loss Function Over.
2024-05-05_02:49:57 INFO: Train Model Start.
2024-05-05_02:49:57 INFO: Learn Name: trainCross
2024-05-05_02:49:57 INFO: Config: Namespace(adversarial=True, alpha=0.4, b=0.06, batch_size=16, cuda=True, device=0, epoch=20, gamma=3, interval_log=10, interval_test=1, kmer=3, learn_name='trainCross', loss_func='CE', lr=0.0001, mode='train-test', model='ClassificationDNAbert', model_save_name='BERT', num_class=2, num_workers=4, optimizer='AdamW', path_params='../pretrain/DNAbert_3mer/pytorch_model.bin', path_save='../result/', path_test_data='../data/DNA_MS/tsv/5hmC/5hmC_H.sapiens/test.tsv', path_train_data='../data/DNA_MS/tsv/5hmC/5hmC_H.sapiens/train.tsv', reg=0.003, save_best=False, save_figure_type='png', test_name=None, threshold=0.95, train_name=None)
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    SL_train(config)
  File "train.py", line 30, in SL_train
    learner.train_model()
  File "/leonardo/home/userexternal/ablindu0/iDNA_ABF_bis/iDNA_ABF/frame/Learner.py", line 53, in train_model
    self.modelManager.train()
  File "/leonardo/home/userexternal/ablindu0/iDNA_ABF_bis/iDNA_ABF/frame/ModelManager.py", line 91, in train
    best_performance, best_repres_list, best_label_list, ROC, PRC = self.__SL_train(train_dataloader,
  File "/leonardo/home/userexternal/ablindu0/iDNA_ABF_bis/iDNA_ABF/frame/ModelManager.py", line 302, in __SL_train
    train_loss = self.__get_loss(logits, label)
  File "/leonardo/home/userexternal/ablindu0/iDNA_ABF_bis/iDNA_ABF/frame/ModelManager.py", line 157, in __get_loss
    loss = self.loss_func(logits.view(-1, self.config.num_class), label.view(-1))
  File "/leonardo/home/userexternal/ablindu0/miniconda3/envs/dna_clone_3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/leonardo/home/userexternal/ablindu0/miniconda3/envs/dna_clone_3/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1174, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/leonardo/home/userexternal/ablindu0/miniconda3/envs/dna_clone_3/lib/python3.8/site-packages/torch/nn/functional.py", line 3026, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
ValueError: Expected input batch_size (64) to match target batch_size (16).```

**Comment by FakeEnd** [comment]
Sorry, becasue I can not reproduce this bug, I don't know why this happens. 

My torch version is 2.0.0. I suggest use new torch version to have a try. Maybe it can help as it is a problem caused by torch.

**Comment by AndreiBlindu** [comment]
> Sorry, becasue I can not reproduce this bug, I don't know why this happens.
> 
> My torch version is 2.0.0. I suggest use new torch version to have a try. Maybe it can help as it is a problem caused by torch.

Even upgrading torch to 2.0.0 (I previously had 1.13.0), I still have the same issue.
Can you please provide me the versions you are using of the other relevant packages to be sure I'm using the same versions as you?

What are you using as pretrained model? I'm using the weights of the pretrained DNABERT models (with kmers 3,4,5,6) downloaded from Huggingface.

Thanks for the assistance

**Comment by FakeEnd** [comment]
OK, I have reproduced your bug and know where the problem. (In my previous code,  I still have this option in my code os.environ["CUDA_VISIBLE_DEVICES"] = str(config.device))

I will create a branch using  multi-GPU later today to update code.

**Comment by AndreiBlindu** [comment]
> OK, I have reproduced your bug and know where the problem. (In my previous code, I still have this option in my code os.environ["CUDA_VISIBLE_DEVICES"] = str(config.device))
> 
> I will create a branch using multi-GPU later today to update code.

Thank you very much, that's a great idea! 
I'll wait for the multi-GPU branch then

**Comment by FakeEnd** [comment]
> > OK, I have reproduced your bug and know where the problem. (In my previous code, I still have this option in my code os.environ["CUDA_VISIBLE_DEVICES"] = str(config.device))
> > I will create a branch using multi-GPU later today to update code.
> 
> Thank you very much, that's a great idea! I'll wait for the multi-GPU branch then

I have uploaded it (https://github.com/FakeEnd/iDNA_ABF/tree/multi-GPU). You can have a try. Hope it can work well 😄 

But I found the there will have slight decrease in performance.

**Comment by AndreiBlindu** [comment]
> > > OK, I have reproduced your bug and know where the problem. (In my previous code, I still have this option in my code os.environ["CUDA_VISIBLE_DEVICES"] = str(config.device))
> > > I will create a branch using multi-GPU later today to update code.
> > 
> > 
> > Thank you very much, that's a great idea! I'll wait for the multi-GPU branch then
> 
> I have uploaded it (https://github.com/FakeEnd/iDNA_ABF/tree/multi-GPU). You can have a try. Hope it can work well 😄
> 
> But I found the there will have slight decrease in performance.

I tried the multi-GPU code and it works like a charm! Thank you very much 😁

The only issue is that if I try using 2 different nodes (with 4 GPU per node) only the first node works, even if I add all the devices to
```os.environ["CUDA_VISIBLE_DEVICES"] = "0, 1, 2, 3, 4, 5, 6, 7"```

Have you ever tried on multiple nodes?

**Comment by FakeEnd** [comment]
It is more complicated to train on multiple nodes. Sorry, I didn't try it before and I have no access to multi-nodes.

Here just some suggestions: If you want to use multi-nodes, you must have a node as a master to communicate with others.

https://pytorch.org/tutorials/intermediate/ddp_series_multinode.html (hope can help you)

**Comment by AndreiBlindu** [comment]
> It is more complicated to train on multiple nodes. Sorry, I didn't try it before and I have no access to multi-nodes.
> 
> Here just some suggestions: If you want to use multi-nodes, you must have a node as a master to communicate with others.
> 
> https://pytorch.org/tutorials/intermediate/ddp_series_multinode.html (hope can help you)

Don't worry and thank you again, I'll try to figure it out!

In the meanwhile I report you this error I got while training the model with 4 GPUs on another dataset (iPromoter), which is related to the last changes you did.
```
Epoch[1] Batch[8400] - loss: 0.176673 | ACC: 87.5000%(14/16)
Traceback (most recent call last):
  File "train.py", line 142, in <module>
    SL_train(config)
  File "train.py", line 30, in SL_train
    learner.train_model()
  File "/leonardo/home/userexternal/ablindu0/iDNA_ABF_bis/multi_gpu/iDNA_ABF/frame/Learner.py", line 53, in train_model
    self.modelManager.train()
  File "/leonardo/home/userexternal/ablindu0/iDNA_ABF_bis/multi_gpu/iDNA_ABF/frame/ModelManager.py", line 90, in train
    best_performance, best_repres_list, best_label_list, ROC, PRC = self.__SL_train(train_dataloader,
  File "/leonardo/home/userexternal/ablindu0/iDNA_ABF_bis/multi_gpu/iDNA_ABF/frame/ModelManager.py", line 320, in __SL_train
    logits, _ = self.model(data_tensor.cuda())
  File "/leonardo/home/userexternal/ablindu0/miniconda3/envs/dna_clone_3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/leonardo/home/userexternal/ablindu0/miniconda3/envs/dna_clone_3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/leonardo/home/userexternal/ablindu0/miniconda3/envs/dna_clone_3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/leonardo/home/userexternal/ablindu0/miniconda3/envs/dna_clone_3/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/leonardo/home/userexternal/ablindu0/miniconda3/envs/dna_clone_3/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
KeyError: Caught KeyError in replica 2 on device 2.
Original Traceback (most recent call last):
  File "/leonardo/home/userexternal/ablindu0/miniconda3/envs/dna_clone_3/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/leonardo/home/userexternal/ablindu0/miniconda3/envs/dna_clone_3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/leonardo/home/userexternal/ablindu0/iDNA_ABF_bis/multi_gpu/iDNA_ABF/model/FusionDNAbert.py", line 42, in forward
    seqs = self.index2seq(index)
  File "/leonardo/home/userexternal/ablindu0/iDNA_ABF_bis/multi_gpu/iDNA_ABF/model/FusionDNAbert.py", line 37, in index2seq
    seq = ''.join([index2char[j.item()] for j in i])
  File "/leonardo/home/userexternal/ablindu0/iDNA_ABF_bis/multi_gpu/iDNA_ABF/model/FusionDNAbert.py", line 37, in <listcomp>
    seq = ''.join([index2char[j.item()] for j in i])
KeyError: 4
```

**Comment by FakeEnd** [comment]
This problem is may casused by N in your dataset. Now I only token A C T G.

You can change code here https://github.com/FakeEnd/iDNA_ABF/blob/34eb3ae2a4eef1f7dcd5b3c8fbdd69ca4574f66a/frame/ModelManager.py#L297
and here
https://github.com/FakeEnd/iDNA_ABF/blob/34eb3ae2a4eef1f7dcd5b3c8fbdd69ca4574f66a/model/FusionDNAbert.py#L34

For example: add
`index2char = {0: 'A', 1: 'C', 2: 'G', 3: 'T', 4: 'N'} `

**Comment by AndreiBlindu** [comment]
> This problem is may casused by N in your dataset. Now I only token A C T G.
> 
> You can change code here
> 
> https://github.com/FakeEnd/iDNA_ABF/blob/34eb3ae2a4eef1f7dcd5b3c8fbdd69ca4574f66a/frame/ModelManager.py#L297
> 
> 
> and here
> https://github.com/FakeEnd/iDNA_ABF/blob/34eb3ae2a4eef1f7dcd5b3c8fbdd69ca4574f66a/model/FusionDNAbert.py#L34
> 
> For example: add `index2char = {0: 'A', 1: 'C', 2: 'G', 3: 'T', 4: 'N'} `

Ok this fixed the issue. Thank you very much for the assistance
